### ISSUE TITLE
查询报错Cannot connect to host bawiki.lgc2333.top:443

### ISSUE THREAD

**Issue by A7424** [lgc2333/nonebot-plugin-bawiki#26]
[04-10 01:41:31 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_bawiki.__main__) failed.
Traceback (most recent call last):
  File "D:\jqr\nonebot2\nb2\.venv\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "C:\Users\QC\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 1050, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "C:\Users\QC\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 1080, in _create_connection_transport
    await waiter
  File "C:\Users\QC\AppData\Local\Programs\Python\Python38\lib\asyncio\sslproto.py", line 529, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "C:\Users\QC\AppData\Local\Programs\Python\Python38\lib\asyncio\sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "C:\Users\QC\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 944, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'bawiki.lgc2333.top'. (_ssl.c:1131)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "bot.py", line 17, in <module>
    nonebot.run()
  File "D:\jqr\nonebot2\nb2\.venv\lib\site-packages\nonebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "D:\jqr\nonebot2\nb2\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 187, in run
    uvicorn.run(
  File "D:\jqr\nonebot2\nb2\.venv\lib\site-packages\uvicorn\main.py", line 568, in run
    server.run()
  File "D:\jqr\nonebot2\nb2\.venv\lib\site-packages\uvicorn\server.py", line 59, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\QC\AppData\Local\Programs\Python\Python38\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\QC\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "C:\Users\QC\AppData\Local\Programs\Python\Python38\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\QC\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "C:\Users\QC\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "C:\Users\QC\AppData\Local\Programs\Python\Python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "D:\jqr\nonebot2\nb2\.venv\lib\site-packages\nonebot\message.py", line 141, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "D:\jqr\nonebot2\nb2\.venv\lib\site-packages\nonebot\message.py", line 187, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "D:\jqr\nonebot2\nb2\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 732, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "D:\jqr\nonebot2\nb2\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 707, in simple_run
    await handler(
  File "D:\jqr\nonebot2\nb2\.venv\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "D:\jqr\nonebot2\nb2\.venv\lib\site-packages\nonebot_plugin_bawiki\__main__.py", line 253, in _
    arg = await recover_stu_alia(arg)
  File "D:\jqr\nonebot2\nb2\.venv\lib\site-packages\nonebot_plugin_bawiki\data_bawiki.py", line 72, in recover_stu_alia
    ret = recover_alia(a, await db_get_stu_alias())
  File "D:\jqr\nonebot2\nb2\.venv\lib\site-packages\nonebot_plugin_bawiki\data_bawiki.py", line 29, in db_get_stu_alias
    return await db_get("data/stu_alias.json")
  File "D:\jqr\nonebot2\nb2\.venv\lib\site-packages\nonebot_plugin_bawiki\data_bawiki.py", line 21, in db_get
    return await async_req(f"{BAWIKI_DB_URL}{suffix}", raw=raw)
  File "D:\jqr\nonebot2\nb2\.venv\lib\site-packages\nonebot_plugin_bawiki\util.py", line 72, in async_req
    async with c.request(method, url, **kwargs, proxy=proxy) as r:
  File "D:\jqr\nonebot2\nb2\.venv\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\jqr\nonebot2\nb2\.venv\lib\site-packages\aiohttp\client.py", line 536, in _request
    conn = await self._connector.connect(
  File "D:\jqr\nonebot2\nb2\.venv\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\jqr\nonebot2\nb2\.venv\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\jqr\nonebot2\nb2\.venv\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\jqr\nonebot2\nb2\.venv\lib\site-packages\aiohttp\connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "D:\jqr\nonebot2\nb2\.venv\lib\site-packages\aiohttp\connector.py", line 982, in _wrap_create_connection
    raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host bawiki.lgc2333.top:443 ssl:True [SSLCertVerificationError: (1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'bawiki.lgc2333.top'. (_ssl.c:1131)")]](url)

**Comment by A7424** [comment]
![`E 1 )@U(W`{3}3UKYFHGCG](https://user-images.githubusercontent.com/103619507/230788527-d2b1591a-7303-4695-8af0-4d3a0bfca875.png)

**Comment by lgc2333** [comment]
https://github.com/lgc2333/nonebot-plugin-bawiki/issues/24#issuecomment-1487176128

更新，上CDN了

**Comment by A7424** [comment]
> [#24 (comment)](https://github.com/lgc2333/nonebot-plugin-bawiki/issues/24#issuecomment-1487176128)
> 
> 更新，上CDN了

试过更新了，大概前几分钟重装过一次，用的nb命令输入插件名字安装的

**Comment by lgc2333** [comment]
> > [#24 (comment)](https://github.com/lgc2333/nonebot-plugin-bawiki/issues/24#issuecomment-1487176128)
> > 更新，上CDN了
> 
> 试过更新了，大概前几分钟重装过一次，用的nb命令输入插件名字安装的

你自定义插件数据源了？我刚刚把cf的配置改回去了，原域名现在正常了

**Comment by A7424** [comment]
> > > [#24 (comment)](https://github.com/lgc2333/nonebot-plugin-bawiki/issues/24#issuecomment-1487176128)
> > > 更新，上CDN了
> > 
> > 
> > 试过更新了，大概前几分钟重装过一次，用的nb命令输入插件名字安装的
> 
> 你自定义插件数据源了？我刚刚把cf的配置改回去了，原域名现在正常了

没，只改过.eve
![`OJP$F(KRGB5Z6(C~C41HDV](https://user-images.githubusercontent.com/103619507/230788867-96e30892-0023-4b6f-b940-fe6c945867ea.png)

**Comment by A7424** [comment]
> > > > [#24 (comment)](https://github.com/lgc2333/nonebot-plugin-bawiki/issues/24#issuecomment-1487176128)
> > > > 更新，上CDN了
> > > 
> > > 
> > > 试过更新了，大概前几分钟重装过一次，用的nb命令输入插件名字安装的
> > 
> > 
> > 你自定义插件数据源了？我刚刚把cf的配置改回去了，原域名现在正常了
> 
> 没，只改过.eve ![`OJP$F(KRGB5Z6(C~C41HDV](https://user-images.githubusercontent.com/103619507/230788867-96e30892-0023-4b6f-b940-fe6c945867ea.png)

试过挂梯子

**Comment by lgc2333** [comment]
> > > > > [#24 (comment)](https://github.com/lgc2333/nonebot-plugin-bawiki/issues/24#issuecomment-1487176128)
> > > > > 更新，上CDN了
> > > > 
> > > > 
> > > > 试过更新了，大概前几分钟重装过一次，用的nb命令输入插件名字安装的
> > > 
> > > 
> > > 你自定义插件数据源了？我刚刚把cf的配置改回去了，原域名现在正常了
> > 
> > 
> > 没，只改过.eve ![`OJP$F(KRGB5Z6(C~C41HDV](https://user-images.githubusercontent.com/103619507/230788867-96e30892-0023-4b6f-b940-fe6c945867ea.png)
> 
> 试过挂梯子

不是必选的配置项就不要改，你这确实把url都改回去了，db url还搞错了

**Comment by lgc2333** [comment]
不过原域名应该没问题了，我先close了，还有问题可以接着comment

**Comment by A7424** [comment]
> > > > > > [#24 (comment)](https://github.com/lgc2333/nonebot-plugin-bawiki/issues/24#issuecomment-1487176128)
> > > > > > 更新，上CDN了
> > > > > 
> > > > > 
> > > > > 试过更新了，大概前几分钟重装过一次，用的nb命令输入插件名字安装的
> > > > 
> > > > 
> > > > 你自定义插件数据源了？我刚刚把cf的配置改回去了，原域名现在正常了
> > > 
> > > 
> > > 没，只改过.eve ![`OJP$F(KRGB5Z6(C~C41HDV](https://user-images.githubusercontent.com/103619507/230788867-96e30892-0023-4b6f-b940-fe6c945867ea.png)
> > 
> > 
> > 试过挂梯子
> 
> 不是必选的配置项就不要改，你这确实把url都改回去了，db url还搞错了

好的，我改回去再尝试
